FROM python:3.8.9-alpine

WORKDIR /ml

COPY requirements.txt ./

COPY . .

RUN pip install -r requirements.txt

RUN apk add npm

RUN npm install -g nodemon

CMD nodemon --exec "python -u" realtime.py
