version: '3'
services:
    webapp:
        container_name: node-webapp-1
        build: ./webapp
        environment:
            TEST: 1234
        ports:
            - "3000:3000"
            - "3001:3001"
        volumes:
            - ./webapp/:/webapp
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:3001"]
            interval: 30s
            timeout: 10s
            retries: 10
        command: yarn dev
    
    ml:
        container_name: python-ml-1
        build:
            context: ./ml
            dockerfile: Dockerfile.prod
        environment:
            SOCKET_URL: http://webapp:3001
        volumes:
            - ./ml/:/ml
