version: '3'
services:
    webapp:
        container_name: node-webapp-1
        build: ./webapp
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:3001"]
            interval: 30s
            timeout: 10s
            retries: 10
    
    ml:
        container_name: python-ml-1
        restart: always
        depends_on:
            webapp:
                condition: service_healthy
        