version: '3'
services:
    webapp:
        environment:
            TEST: 1234
        ports:
            - "3000:3000"
            - "3001:3001"
        volumes:
            - ./webapp/:/webapp
            - /webapp/node_modules
            - /webapp/packages/client/node_modules
    ml:
        build:
            context: ./ml
            dockerfile: Dockerfile.dev
        environment:
            SOCKET_URL: http://webapp:3001
        volumes:
            - ./ml:/ml