version: '3'
services:
    webapp:
        container_name: node-webapp-1
        build: ./webapp
        restart: always
        environment:
            TEST: 1234
        ports:
            - "3000:3000"
            - "3001:3001"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:3001"]
            interval: 30s
            timeout: 10s
            retries: 10
    
    ml:
        container_name: python-ml-1
        build: ./ml
        restart: always
        environment:
            SOCKET_URL: http://webapp:3001
        depends_on:
            webapp:
                condition: service_healthy

